### ISSUE TITLE
Add this provider to registry

### ISSUE THREAD

**Issue by lexfrei** [mhumeSF/terraform-provider-namedotcom#9]
Hi!
Add this provider to the registry, please!
[Add page](https://registry.terraform.io/publish/provider), [manual](https://www.terraform.io/registry/providers/publishing).

**Comment by lexfrei** [comment]
Added by myself. https://registry.terraform.io/providers/lexfrei/namedotcom/latest

**Comment by mhumeSF** [comment]
@lexfrei Nice work. I'm going to archive this repo as yours looks more up to date.
